<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\State;
use App\Models\City;

class EgyptStatesAndCitiesSeeder extends Seeder
{
    public function run(): void
    {
        //delete all states and cities first
        State::withoutGlobalScope('active')->delete();
        City::withoutGlobalScope('active')->delete();

        $data = [
            [
                'name_ar' => 'القاهرة',
                'name_en' => 'Cairo',
                'cities' => [
                    ['name_ar' => 'باقي أحياء القاهرة',  'name_en' => 'Other Cairo Districts'],
                    ['name_ar' => 'حلوان',                'name_en' => 'Helwan'],
                    ['name_ar' => '15 مايو',              'name_en' => '15th of May City'],
                    ['name_ar' => 'الرحاب',               'name_en' => 'Al Rehab'],
                    ['name_ar' => 'الشروق',               'name_en' => 'Al Shorouk'],
                    ['name_ar' => 'العاصمة الإدارية',    'name_en' => 'New Administrative Capital'],
                    ['name_ar' => 'القاهرة الجديدة',     'name_en' => 'New Cairo'],
                    ['name_ar' => 'بدر',                  'name_en' => 'Badr City'],
                ],
            ],
            [
                'name_ar' => 'الإسكندرية',
                'name_en' => 'Alexandria',
                'cities' => [
                    ['name_ar' => 'باقي أحياء الإسكندرية', 'name_en' => 'Other Alexandria Districts'],
                    ['name_ar' => 'برج العرب',              'name_en' => 'Borg El Arab'],
                    ['name_ar' => 'برج العرب الجديدة',      'name_en' => 'New Borg El Arab'],
                    ['name_ar' => 'الساحل الشمالي',         'name_en' => 'North Coast'],
                ],
            ],
            [
                'name_ar' => 'الجيزة',
                'name_en' => 'Giza',
                'cities' => [
                    ['name_ar' => 'باقي أحياء الجيزة', 'name_en' => 'Other Giza Districts'],
                    ['name_ar' => '6 أكتوبر',           'name_en' => '6th of October City'],
                    ['name_ar' => 'البدرشين',            'name_en' => 'Al Badrasheen'],
                    ['name_ar' => 'الحوامدية',           'name_en' => 'Al Hawamdiyya'],
                    ['name_ar' => 'الربوة',              'name_en' => 'Al Rabwa'],
                    ['name_ar' => 'الشيخ زايد',          'name_en' => 'Sheikh Zayed'],
                    ['name_ar' => 'الصف',                'name_en' => 'Al Saff'],
                    ['name_ar' => 'العياط',              'name_en' => 'Al Ayat'],
                    ['name_ar' => 'الواحات البحرية',     'name_en' => 'Bahariya Oasis'],
                    ['name_ar' => 'أطفيح',               'name_en' => 'Atfih'],
                    ['name_ar' => 'أوسيم',               'name_en' => 'Ausim'],
                    ['name_ar' => 'كرداسة',              'name_en' => 'Kerdasa'],
                    ['name_ar' => 'منشأة القناطر',       'name_en' => 'Manshiyet Al Qanater'],
                ],
            ],
            [
                'name_ar' => 'القليوبية',
                'name_en' => 'Qalyubia',
                'cities' => [
                    ['name_ar' => 'بنها',               'name_en' => 'Banha'],
                    ['name_ar' => 'الخانكة',            'name_en' => 'Al Khanka'],
                    ['name_ar' => 'الخصوص',             'name_en' => 'Al Khosous'],
                    ['name_ar' => 'العبور',              'name_en' => 'Al Obour'],
                    ['name_ar' => 'القناطر الخيرية',    'name_en' => 'Al Qanater Al Khayria'],
                    ['name_ar' => 'شبرا الخيمة',        'name_en' => 'Shubra Al Khayma'],
                    ['name_ar' => 'شبين القناطر',       'name_en' => 'Shibin Al Qanater'],
                    ['name_ar' => 'طوخ',                'name_en' => 'Tukh'],
                    ['name_ar' => 'قليوب',              'name_en' => 'Qaliub'],
                    ['name_ar' => 'قها',                'name_en' => 'Qaha'],
                    ['name_ar' => 'كفر شكر',            'name_en' => 'Kafr Shukr'],
                ],
            ],
            [
                'name_ar' => 'الغربية',
                'name_en' => 'Gharbia',
                'cities' => [
                    ['name_ar' => 'طنطا',          'name_en' => 'Tanta'],
                    ['name_ar' => 'السنطة',        'name_en' => 'Al Santa'],
                    ['name_ar' => 'المحلة الكبرى', 'name_en' => 'Al Mahalla Al Kubra'],
                    ['name_ar' => 'بسيون',         'name_en' => 'Bassioun'],
                    ['name_ar' => 'زفتى',          'name_en' => 'Zifta'],
                    ['name_ar' => 'سمنود',         'name_en' => 'Samannoud'],
                    ['name_ar' => 'قطور',          'name_en' => 'Qutour'],
                    ['name_ar' => 'كفر الزيات',   'name_en' => 'Kafr Al Zayyat'],
                ],
            ],
            [
                'name_ar' => 'الشرقية',
                'name_en' => 'Sharqia',
                'cities' => [
                    ['name_ar' => 'الزقازيق',         'name_en' => 'Zagazig'],
                    ['name_ar' => 'الإبراهيمية',      'name_en' => 'Al Ibrahimiyya'],
                    ['name_ar' => 'الحسينية',         'name_en' => 'Al Husseiniyya'],
                    ['name_ar' => 'الصالحية الجديدة', 'name_en' => 'New Al Salhia'],
                    ['name_ar' => 'العاشر من رمضان',  'name_en' => '10th of Ramadan City'],
                    ['name_ar' => 'القرين',           'name_en' => 'Al Qurayn'],
                    ['name_ar' => 'القنايات',         'name_en' => 'Al Qanayat'],
                    ['name_ar' => 'أبو حماد',         'name_en' => 'Abu Hammad'],
                    ['name_ar' => 'أبو كبير',         'name_en' => 'Abu Kabir'],
                    ['name_ar' => 'أولاد صقر',        'name_en' => 'Awlad Saqr'],
                    ['name_ar' => 'بلبيس',            'name_en' => 'Bilbeis'],
                    ['name_ar' => 'صان الحجر',        'name_en' => 'San Al Hajar'],
                    ['name_ar' => 'فاقوس',            'name_en' => 'Faqous'],
                    ['name_ar' => 'مشتول السوق',      'name_en' => 'Mashtoul Al Souq'],
                    ['name_ar' => 'منشأة أبو عمر',   'name_en' => 'Manshiyet Abu Omar'],
                    ['name_ar' => 'منيا القمح',       'name_en' => 'Minya Al Qamh'],
                    ['name_ar' => 'ههيا',             'name_en' => 'Hihya'],
                ],
            ],
            [
                'name_ar' => 'الدقهلية',
                'name_en' => 'Dakahlia',
                'cities' => [
                    ['name_ar' => 'المنصورة',         'name_en' => 'Mansoura'],
                    ['name_ar' => 'الجمالية',         'name_en' => 'Al Gamaliyya'],
                    ['name_ar' => 'السنبلاوين',       'name_en' => 'Sinbillawayn'],
                    ['name_ar' => 'الكردي',           'name_en' => 'Al Kurdi'],
                    ['name_ar' => 'المطرية',          'name_en' => 'Al Matariyya'],
                    ['name_ar' => 'المنزلة',          'name_en' => 'Al Manzala'],
                    ['name_ar' => 'المنصورة الجديدة', 'name_en' => 'New Mansoura'],
                    ['name_ar' => 'أجا',              'name_en' => 'Aga'],
                    ['name_ar' => 'بلقاس',            'name_en' => 'Bilqas'],
                    ['name_ar' => 'بني عبيد',         'name_en' => 'Bani Ubaid'],
                    ['name_ar' => 'تمي الأمديد',      'name_en' => 'Tami Al Amdid'],
                    ['name_ar' => 'جمصة',             'name_en' => 'Gamasa'],
                    ['name_ar' => 'دكرنس',            'name_en' => 'Dekernes'],
                    ['name_ar' => 'شربين',            'name_en' => 'Sherbin'],
                    ['name_ar' => 'طلخا',             'name_en' => 'Talha'],
                    ['name_ar' => 'محلة دمنة',        'name_en' => 'Mahallet Damna'],
                    ['name_ar' => 'منية النصر',       'name_en' => 'Minyet Al Nasr'],
                    ['name_ar' => 'ميت سلسيل',        'name_en' => 'Mit Salsil'],
                    ['name_ar' => 'ميت غمر',          'name_en' => 'Mit Ghamr'],
                    ['name_ar' => 'نبروه',            'name_en' => 'Nabruh'],
                ],
            ],
            [
                'name_ar' => 'كفر الشيخ',
                'name_en' => 'Kafr Al Sheikh',
                'cities' => [
                    ['name_ar' => 'كفر الشيخ',  'name_en' => 'Kafr Al Sheikh'],
                    ['name_ar' => 'الحامول',    'name_en' => 'Al Hamoul'],
                    ['name_ar' => 'الرياض',     'name_en' => 'Al Riyad'],
                    ['name_ar' => 'برج البرلس', 'name_en' => 'Burj Al Burullus'],
                    ['name_ar' => 'بلطيم',      'name_en' => 'Baltim'],
                    ['name_ar' => 'بيلا',       'name_en' => 'Bila'],
                    ['name_ar' => 'دسوق',       'name_en' => 'Disuq'],
                    ['name_ar' => 'سيدي سالم',  'name_en' => 'Sidi Salem'],
                    ['name_ar' => 'سيدي غازي',  'name_en' => 'Sidi Ghazi'],
                    ['name_ar' => 'صيد عريقة',  'name_en' => 'Syed Ariqa'],
                    ['name_ar' => 'فوّه',        'name_en' => 'Fuwwah'],
                    ['name_ar' => 'قلّين',       'name_en' => 'Qallin'],
                    ['name_ar' => 'مسير',       'name_en' => 'Maseer'],
                    ['name_ar' => 'مطوبس',      'name_en' => 'Mutubas'],
                ],
            ],
            [
                'name_ar' => 'البحيرة',
                'name_en' => 'Beheira',
                'cities' => [
                    ['name_ar' => 'دمنهور',            'name_en' => 'Damanhur'],
                    ['name_ar' => 'الدلنجات',          'name_en' => 'Al Delengat'],
                    ['name_ar' => 'الرحمانية',         'name_en' => 'Al Rahmaniyya'],
                    ['name_ar' => 'المحمودية',         'name_en' => 'Al Mahmoudiyya'],
                    ['name_ar' => 'النوبارية الجديدة', 'name_en' => 'New Nubaria'],
                    ['name_ar' => 'إتاي البارود',      'name_en' => 'Itay Al Baroud'],
                    ['name_ar' => 'إدكو',              'name_en' => 'Edku'],
                    ['name_ar' => 'أبو المطامير',      'name_en' => 'Abu Al Matamir'],
                    ['name_ar' => 'أبو حمص',           'name_en' => 'Abu Homs'],
                    ['name_ar' => 'بدر',               'name_en' => 'Badr'],
                    ['name_ar' => 'حوش عيسى',          'name_en' => 'Hawsh Issa'],
                    ['name_ar' => 'رشيد',              'name_en' => 'Rashid (Rosetta)'],
                    ['name_ar' => 'شبراخيت',           'name_en' => 'Shabrakheit'],
                    ['name_ar' => 'كفر الدوار',        'name_en' => 'Kafr Al Dawwar'],
                    ['name_ar' => 'كوم حمادة',         'name_en' => 'Kom Hamada'],
                    ['name_ar' => 'وادي النطرون',      'name_en' => 'Wadi Al Natrun'],
                ],
            ],
            [
                'name_ar' => 'دمياط',
                'name_en' => 'Damietta',
                'cities' => [
                    ['name_ar' => 'دمياط',         'name_en' => 'Damietta'],
                    ['name_ar' => 'الروضة',        'name_en' => 'Al Rawda'],
                    ['name_ar' => 'الزرقا',        'name_en' => 'Al Zarqa'],
                    ['name_ar' => 'السرو',         'name_en' => 'Al Saru'],
                    ['name_ar' => 'دمياط الجديدة', 'name_en' => 'New Damietta'],
                    ['name_ar' => 'رأس البر',      'name_en' => 'Ras Al Bar'],
                    ['name_ar' => 'عزبة البرج',    'name_en' => 'Azbet Al Burg'],
                    ['name_ar' => 'فارسكور',       'name_en' => 'Faraskur'],
                    ['name_ar' => 'كفر البطيخ',   'name_en' => 'Kafr Al Battikh'],
                    ['name_ar' => 'كفر سعد',       'name_en' => 'Kafr Saad'],
                    ['name_ar' => 'ميت أبو غالب',  'name_en' => 'Mit Abu Ghalib'],
                ],
            ],
            [
                'name_ar' => 'المنوفية',
                'name_en' => 'Monufia',
                'cities' => [
                    ['name_ar' => 'شبين الكوم',   'name_en' => 'Shibin Al Kom'],
                    ['name_ar' => 'الباجور',      'name_en' => 'Al Bagour'],
                    ['name_ar' => 'السادات',      'name_en' => 'Sadat City'],
                    ['name_ar' => 'الشهداء',      'name_en' => 'Al Shohada'],
                    ['name_ar' => 'أشمون',        'name_en' => 'Ashmoun'],
                    ['name_ar' => 'بركة السبع',   'name_en' => 'Birket Al Sab'],
                    ['name_ar' => 'تلا',          'name_en' => 'Tala'],
                    ['name_ar' => 'سرس الليان',   'name_en' => 'Sirs Al Layyana'],
                    ['name_ar' => 'مدينة قويسنا', 'name_en' => 'Quesna'],
                    ['name_ar' => 'منوف',         'name_en' => 'Menuf'],
                ],
            ],
            [
                'name_ar' => 'مطروح',
                'name_en' => 'Matrouh',
                'cities' => [
                    ['name_ar' => 'مرسى مطروح',       'name_en' => 'Marsa Matrouh'],
                    ['name_ar' => 'الحمام',            'name_en' => 'Al Hammam'],
                    ['name_ar' => 'السلوم',            'name_en' => 'Al Salloum'],
                    ['name_ar' => 'الضبعة',            'name_en' => 'Al Dabaa'],
                    ['name_ar' => 'العلمين',           'name_en' => 'Al Alamein'],
                    ['name_ar' => 'العلمين الجديدة',  'name_en' => 'New Alamein'],
                    ['name_ar' => 'النجيلة',           'name_en' => 'Al Nagila'],
                    ['name_ar' => 'سيدي براني',        'name_en' => 'Sidi Barrani'],
                    ['name_ar' => 'سيدي عبد الرحمن',  'name_en' => 'Sidi Abd Al Rahman'],
                    ['name_ar' => 'سيوة',              'name_en' => 'Siwa'],
                ],
            ],
            [
                'name_ar' => 'بور سعيد',
                'name_en' => 'Port Said',
                'cities' => [
                    ['name_ar' => 'بور سعيد',         'name_en' => 'Port Said'],
                    ['name_ar' => 'بور سعيد الجديدة', 'name_en' => 'New Port Said'],
                    ['name_ar' => 'بور فؤاد',         'name_en' => 'Port Fouad'],
                ],
            ],
            [
                'name_ar' => 'الإسماعيلية',
                'name_en' => 'Ismailia',
                'cities' => [
                    ['name_ar' => 'الإسماعيلية',         'name_en' => 'Ismailia'],
                    ['name_ar' => 'الإسماعيلية الجديدة', 'name_en' => 'New Ismailia'],
                    ['name_ar' => 'التل الكبير',          'name_en' => 'Al Tal Al Kabir'],
                    ['name_ar' => 'القصاصين الجديدة',    'name_en' => 'New Al Qassasin'],
                    ['name_ar' => 'القنطرة شرق',          'name_en' => 'Al Qantara East'],
                    ['name_ar' => 'القنطرة غرب',          'name_en' => 'Al Qantara West'],
                    ['name_ar' => 'أبو صوير',             'name_en' => 'Abu Suwayr'],
                    ['name_ar' => 'فايد',                 'name_en' => 'Fayed'],
                ],
            ],
            [
                'name_ar' => 'السويس',
                'name_en' => 'Suez',
                'cities' => [
                    ['name_ar' => 'السويس', 'name_en' => 'Suez'],
                ],
            ],
            [
                'name_ar' => 'جنوب سيناء',
                'name_en' => 'South Sinai',
                'cities' => [
                    ['name_ar' => 'الطور',        'name_en' => 'Al Tor'],
                    ['name_ar' => 'أبو رديس',     'name_en' => 'Abu Rudeis'],
                    ['name_ar' => 'أبو زنيمة',   'name_en' => 'Abu Zneima'],
                    ['name_ar' => 'دهب',          'name_en' => 'Dahab'],
                    ['name_ar' => 'رأس سدر',      'name_en' => 'Ras Sidr'],
                    ['name_ar' => 'سانت كاترين',  'name_en' => 'Saint Catherine'],
                    ['name_ar' => 'شرم الشيخ',   'name_en' => 'Sharm El Sheikh'],
                    ['name_ar' => 'طابا',         'name_en' => 'Taba'],
                    ['name_ar' => 'نويبع',        'name_en' => 'Nuweiba'],
                ],
            ],
            [
                'name_ar' => 'شمال سيناء',
                'name_en' => 'North Sinai',
                'cities' => [
                    ['name_ar' => 'العريش',      'name_en' => 'Arish'],
                    ['name_ar' => 'الحسنة',      'name_en' => 'Al Hassana'],
                    ['name_ar' => 'الشيخ زويد',  'name_en' => 'Sheikh Zuweid'],
                    ['name_ar' => 'بئر العبد',   'name_en' => 'Bir Al Abd'],
                    ['name_ar' => 'رفح',         'name_en' => 'Rafah'],
                    ['name_ar' => 'نخل',         'name_en' => 'Nakhl'],
                ],
            ],
            [
                'name_ar' => 'البحر الأحمر',
                'name_en' => 'Red Sea',
                'cities' => [
                    ['name_ar' => 'الغردقة',    'name_en' => 'Hurghada'],
                    ['name_ar' => 'الجونة',     'name_en' => 'El Gouna'],
                    ['name_ar' => 'العين السخنة','name_en' => 'Ain Sokhna'],
                    ['name_ar' => 'القصير',     'name_en' => 'Al Qusayr'],
                    ['name_ar' => 'حلايب',      'name_en' => 'Halayeb'],
                    ['name_ar' => 'رأس غارب',   'name_en' => 'Ras Gharib'],
                    ['name_ar' => 'سفاجا',      'name_en' => 'Safaga'],
                    ['name_ar' => 'سوما باي',   'name_en' => 'Soma Bay'],
                    ['name_ar' => 'شلاتين',     'name_en' => 'Shalatin'],
                    ['name_ar' => 'مرسى علم',   'name_en' => 'Marsa Alam'],
                    ['name_ar' => 'مكادي باي',  'name_en' => 'Makadi Bay'],
                ],
            ],
            [
                'name_ar' => 'الفيوم',
                'name_en' => 'Fayoum',
                'cities' => [
                    ['name_ar' => 'الفيوم',        'name_en' => 'Fayoum'],
                    ['name_ar' => 'إبشواي',        'name_en' => 'Ibshaway'],
                    ['name_ar' => 'إطسا',          'name_en' => 'Itsa'],
                    ['name_ar' => 'سنورس',         'name_en' => 'Sinnuris'],
                    ['name_ar' => 'طامية',         'name_en' => 'Tamiya'],
                    ['name_ar' => 'يوسف الصديق',  'name_en' => 'Yusuf Al Siddiq'],
                ],
            ],
            [
                'name_ar' => 'بني سويف',
                'name_en' => 'Beni Suef',
                'cities' => [
                    ['name_ar' => 'بني سويف',         'name_en' => 'Beni Suef'],
                    ['name_ar' => 'الفشن',            'name_en' => 'Al Fashn'],
                    ['name_ar' => 'الواسطى',          'name_en' => 'Al Wasta'],
                    ['name_ar' => 'إهناسيا',          'name_en' => 'Ihnasiya'],
                    ['name_ar' => 'ببا',              'name_en' => 'Biba'],
                    ['name_ar' => 'بني سويف الجديدة', 'name_en' => 'New Beni Suef'],
                    ['name_ar' => 'سمسطا',            'name_en' => 'Sumusta'],
                    ['name_ar' => 'ناصر (بوش)',       'name_en' => 'Nasser (Bush)'],
                ],
            ],
            [
                'name_ar' => 'المنيا',
                'name_en' => 'Minya',
                'cities' => [
                    ['name_ar' => 'المنيا',         'name_en' => 'Minya'],
                    ['name_ar' => 'الروضة',         'name_en' => 'Al Rawda'],
                    ['name_ar' => 'العدوة',         'name_en' => 'Al Adwa'],
                    ['name_ar' => 'المنيا الجديدة', 'name_en' => 'New Minya'],
                    ['name_ar' => 'أبو قرقاص',      'name_en' => 'Abu Qurqas'],
                    ['name_ar' => 'بني مزار',       'name_en' => 'Bani Mazar'],
                    ['name_ar' => 'دير مواس',       'name_en' => 'Dayr Mawas'],
                    ['name_ar' => 'سمالوط',         'name_en' => 'Samalut'],
                    ['name_ar' => 'مطاي',           'name_en' => 'Matay'],
                    ['name_ar' => 'مغاغة',          'name_en' => 'Maghagha'],
                    ['name_ar' => 'ملوى',           'name_en' => 'Mallawi'],
                    ['name_ar' => 'هامّة',           'name_en' => 'Hamma'],
                ],
            ],
            [
                'name_ar' => 'أسيوط',
                'name_en' => 'Assiut',
                'cities' => [
                    ['name_ar' => 'أسيوط',         'name_en' => 'Assiut'],
                    ['name_ar' => 'البداري',        'name_en' => 'Al Badari'],
                    ['name_ar' => 'الغنايم',        'name_en' => 'Al Ghanaim'],
                    ['name_ar' => 'الفتح',          'name_en' => 'Al Fateh'],
                    ['name_ar' => 'القوصية',        'name_en' => 'Al Qusiyya'],
                    ['name_ar' => 'أبنوب',          'name_en' => 'Abnub'],
                    ['name_ar' => 'أبو تيج',        'name_en' => 'Abu Tij'],
                    ['name_ar' => 'أسيوط الجديدة', 'name_en' => 'New Assiut'],
                    ['name_ar' => 'ديروط',          'name_en' => 'Dayrut'],
                    ['name_ar' => 'ساحل سليم',      'name_en' => 'Sahel Selim'],
                    ['name_ar' => 'صدفا',           'name_en' => 'Sedfa'],
                    ['name_ar' => 'منفلوط',         'name_en' => 'Manfalut'],
                ],
            ],
            [
                'name_ar' => 'سوهاج',
                'name_en' => 'Sohag',
                'cities' => [
                    ['name_ar' => 'سوهاج',         'name_en' => 'Sohag'],
                    ['name_ar' => 'البلينا',        'name_en' => 'Al Balyana'],
                    ['name_ar' => 'العسيرات',       'name_en' => 'Al Usirat'],
                    ['name_ar' => 'المراغة',        'name_en' => 'Al Maragha'],
                    ['name_ar' => 'المنشاه',        'name_en' => 'Al Manshah'],
                    ['name_ar' => 'أخميم',          'name_en' => 'Akhmim'],
                    ['name_ar' => 'جرجا',           'name_en' => 'Gerga'],
                    ['name_ar' => 'جهينة',          'name_en' => 'Juhayna'],
                    ['name_ar' => 'ساقلتة',         'name_en' => 'Saqulta'],
                    ['name_ar' => 'سوهاج الجديدة', 'name_en' => 'New Sohag'],
                    ['name_ar' => 'طما',            'name_en' => 'Tema'],
                    ['name_ar' => 'طهطا',           'name_en' => 'Tahta'],
                ],
            ],
            [
                'name_ar' => 'قنا',
                'name_en' => 'Qena',
                'cities' => [
                    ['name_ar' => 'قنا',           'name_en' => 'Qena'],
                    ['name_ar' => 'ارمنت',         'name_en' => 'Armant'],
                    ['name_ar' => 'الوقف',         'name_en' => 'Al Waqf'],
                    ['name_ar' => 'أبو تشت',       'name_en' => 'Abu Tesht'],
                    ['name_ar' => 'دشنا',          'name_en' => 'Dishna'],
                    ['name_ar' => 'فرشوط',         'name_en' => 'Farshut'],
                    ['name_ar' => 'قفط',           'name_en' => 'Qift'],
                    ['name_ar' => 'قنا الجديدة',   'name_en' => 'New Qena'],
                    ['name_ar' => 'قوص',           'name_en' => 'Qus'],
                    ['name_ar' => 'نجع حمادي',     'name_en' => 'Nag Hammadi'],
                    ['name_ar' => 'نقادة',         'name_en' => 'Naqada'],
                ],
            ],
            [
                'name_ar' => 'الأقصر',
                'name_en' => 'Luxor',
                'cities' => [
                    ['name_ar' => 'الأقصر',        'name_en' => 'Luxor'],
                    ['name_ar' => 'البياضية',      'name_en' => 'Al Bayadiyya'],
                    ['name_ar' => 'الزينية',       'name_en' => 'Al Zayniyya'],
                    ['name_ar' => 'الطود',         'name_en' => 'Al Tod'],
                    ['name_ar' => 'القرنة',        'name_en' => 'Al Qurna'],
                    ['name_ar' => 'إسنا',          'name_en' => 'Esna'],
                    ['name_ar' => 'أرمنت',         'name_en' => 'Armant'],
                    ['name_ar' => 'طيبة الجديدة', 'name_en' => 'New Thebes'],
                ],
            ],
            [
                'name_ar' => 'أسوان',
                'name_en' => 'Aswan',
                'cities' => [
                    ['name_ar' => 'أسوان',        'name_en' => 'Aswan'],
                    ['name_ar' => 'السباعية',     'name_en' => 'Al Sibaiya'],
                    ['name_ar' => 'أبو سمبل',     'name_en' => 'Abu Simbel'],
                    ['name_ar' => 'أدفو',         'name_en' => 'Edfu'],
                    ['name_ar' => 'توشكي',        'name_en' => 'Toshka'],
                    ['name_ar' => 'دراو',         'name_en' => 'Daraw'],
                    ['name_ar' => 'كلابشة',       'name_en' => 'Kalabsha'],
                    ['name_ar' => 'كوم أمبو',     'name_en' => 'Kom Ombo'],
                    ['name_ar' => 'نصر النوبة',   'name_en' => 'Nasr Al Nuba'],
                ],
            ],
            [
                'name_ar' => 'الوادي الجديد',
                'name_en' => 'New Valley',
                'cities' => [
                    ['name_ar' => 'الخارجة', 'name_en' => 'Al Kharga'],
                    ['name_ar' => 'الداخلة', 'name_en' => 'Al Dakhla'],
                    ['name_ar' => 'الفرافرة','name_en' => 'Al Farafra'],
                    ['name_ar' => 'باريس',   'name_en' => 'Paris'],
                    ['name_ar' => 'بلاط',    'name_en' => 'Balat'],
                ],
            ],
        ];
        
        foreach ($data as $stateData) {
            $state = State::create([
                'name_ar'    => $stateData['name_ar'],
                'name_en'    => $stateData['name_en'],
                'is_active'  => true,
                'country_id' => 1,
            ]);

            foreach ($stateData['cities'] as $city) {
                City::create([
                    'name_ar'  => $city['name_ar'],
                    'name_en'  => $city['name_en'],
                    'is_active'=> true,
                    'state_id' => $state->id,
                ]);
            }
        }
    }
}
