<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class MainCatAndCategorySeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('category_translations')->truncate();
        DB::table('categories')->truncate();
        DB::table('main_category_translations')->truncate();
        DB::table('main_categories')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $mainCategories = [
            ['ar' => 'ملابس نسائية', 'en' => 'Women\'s Clothing'],
            ['ar' => 'ملابس رجالي', 'en' => 'Men\'s Clothing'],
            ['ar' => 'ملابس أطفال "بنات"', 'en' => 'Girls\' Clothing'],
            ['ar' => 'ملابس أطفال "أولاد"', 'en' => 'Boys\' Clothing'],
            ['ar' => 'ملابس رياضية', 'en' => 'Sportswear'],
            ['ar' => 'ملابس مهنية', 'en' => 'Professional Uniforms'],
            ['ar' => 'ملابس ومستلزمات المواليد', 'en' => 'Baby Clothes & Accessories'],
            ['ar' => 'شنط وأحزمة ومحافظ', 'en' => 'Bags, Belts & Wallets'],
            ['ar' => 'أحذية جلد', 'en' => 'Leather Shoes'],
            ['ar' => 'أحذية رياضية', 'en' => 'Sports Shoes'],
            ['ar' => 'شباشب وصنادل', 'en' => 'Slippers & Sandals'],
            ['ar' => 'شرابات "جوارب"', 'en' => 'Socks & Stockings'],
            ['ar' => 'أدوات ومستلزمات شخصية', 'en' => 'Personal Tools & Accessories'],
            ['ar' => 'أقمشة ملابس', 'en' => 'Clothing Fabrics'],
            ['ar' => 'أقمشة مفروشات وتنجيد', 'en' => 'Upholstery & Furniture Fabrics'],
            ['ar' => 'مفروشات ومراتب وستائر', 'en' => 'Bedding, Mattresses & Curtains'],
            ['ar' => 'سجاد وفرش أرضيات', 'en' => 'Carpets & Flooring'],
            ['ar' => 'هدايا ومقتنيات متنوعة', 'en' => 'Gifts & Collectibles'],
            ['ar' => 'منتجات عطور وعناية بالجسم', 'en' => 'Perfumes & Body Care'],
            ['ar' => 'منتجات نظافة وعناية بالمنزل', 'en' => 'Home Cleaning & Care Products'],
            ['ar' => 'أثاث وأدوات منزلية وديكورات', 'en' => 'Furniture, Home Tools & Decor'],
            ['ar' => 'أجهزة ومستلزمات المطبخ', 'en' => 'Kitchen Appliances & Supplies'],
            ['ar' => 'أجهزة المنزلية', 'en' => 'Home Appliances'],
            ['ar' => 'شاشات وأجهزة إستقبال وعرض', 'en' => 'TVs, Receivers & Display Devices'],
            ['ar' => 'موبايلات وأجهزة ذكية ومستلزماتها', 'en' => 'Mobile Phones, Smart Devices & Accessories'],
            ['ar' => 'أجهزة ومستلزمات الكمبيوتر', 'en' => 'Computer Devices & Accessories'],
            ['ar' => 'ماكينات تصوير وطباعة واسكانر', 'en' => 'Printers, Scanners & Copiers'],
            ['ar' => 'كاميرات ومستلزمات تصوير', 'en' => 'Cameras & Photography Accessories'],
            ['ar' => 'أجهزة ومستلزمات صوتيات', 'en' => 'Audio Devices & Accessories'],
            ['ar' => 'ساعات', 'en' => 'Watches'],
            ['ar' => 'أنظمة أمن وتتبع ومراقبة وسلامة', 'en' => 'Security, Surveillance & Safety Systems'],
            ['ar' => 'إلكترونيات متنوعة', 'en' => 'Miscellaneous Electronics'],
            ['ar' => 'مستلزمات مكتبية وتعليمية', 'en' => 'Office & Educational Supplies'],
            ['ar' => 'كتب وقصص ومطبوعات', 'en' => 'Books, Stories & Publications'],
            ['ar' => 'منتجات للصحة والطاقة والرجيم', 'en' => 'Health, Energy & Diet Products'],
            ['ar' => 'أجهزة ومستلزمات طبية', 'en' => 'Medical Devices & Supplies'],
            ['ar' => 'أجهزة ومستلزمات رياضة ولياقة وترفيه', 'en' => 'Sports, Fitness & Entertainment Equipment'],
            ['ar' => 'مستلزمات نجارة وسباكة ودهان', 'en' => 'Carpentry, Plumbing & Painting Supplies'],
            ['ar' => 'أطقم حمامات وسيراميك ورخام', 'en' => 'Bathroom Sets, Ceramics & Marble'],
            ['ar' => 'أنظمة ومستلزمات كهرباء وإنارة', 'en' => 'Electrical Systems & Lighting'],
            ['ar' => 'سيارات كهربائية وجولف وبيتش وأطفال', 'en' => 'Electric, Golf, Beach & Kids\' Cars'],
            ['ar' => 'تكاتك وموتوسيكلات ودراجات واسكوترات', 'en' => 'Tuk-tuks, Motorcycles, Bikes & Scooters'],
            ['ar' => 'مستلزمات وكماليات السيارات', 'en' => 'Car Accessories & Extras'],
            ['ar' => 'أثاث شركات ومكاتب', 'en' => 'Office & Commercial Furniture'],
            ['ar' => 'تجهيزات محلات ومعارض ومخازن', 'en' => 'Shop, Showroom & Warehouse Equipment'],
            ['ar' => 'ماكينات وأجهزة ومعدات', 'en' => 'Industrial Machines & Equipment'],
            ['ar' => 'قطع غيار', 'en' => 'Spare Parts'],
            ['ar' => 'ماكينات ومستلزمات الملابس', 'en' => 'Garment Machines & Supplies'],
            ['ar' => 'أعلاف وأطعمة حيوانات وطيور وأسماك', 'en' => 'Animal Feed, Pet Food & Fish Food'],
            ['ar' => 'أسمدة ومواد وأدوات زراعية', 'en' => 'Fertilizers, Agricultural Materials & Tools'],
            ['ar' => 'سوبر ماركت لولو', 'en' => 'Lulu Supermarket'],
        ];

        $mainCategoryIds = [];

        foreach ($mainCategories as $category) {
            $slug = Str::slug($category['en']);

            $mainCategoryId = DB::table('main_categories')->insertGetId([
                'name'       => $category['en'],
                'slug'       => $slug,
                'image'      => null,
                'is_active'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            $mainCategoryIds[$category['ar']] = $mainCategoryId;

            DB::table('main_category_translations')->insert([
                [
                    'main_category_id' => $mainCategoryId,
                    'locale'           => 'ar',
                    'name'             => $category['ar'],
                    'slug'             => $slug . '-ar',
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
                [
                    'main_category_id' => $mainCategoryId,
                    'locale'           => 'en',
                    'name'             => $category['en'],
                    'slug'             => $slug,
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ],
            ]);
        }

        // Each entry: main category Arabic name => [ [ar, en], ... ]
        $data = [
            'ملابس نسائية' => [
                ['ar' => 'ملابس نسائية للخروج',   'en' => 'Women\'s Outerwear'],
                ['ar' => 'ملابس نسائية للبيت',    'en' => 'Women\'s Home Wear'],
                ['ar' => 'ملابس نسائية داخلية',   'en' => 'Women\'s Underwear'],
                ['ar' => 'فساتين عرائس',           'en' => 'Wedding Dresses'],
                ['ar' => 'فساتين سواريه',          'en' => 'Evening Gowns'],
                ['ar' => 'ملابس محجبات',           'en' => 'Hijab Clothing'],
            ],
            'ملابس رجالي' => [
                ['ar' => 'ملابس رجالي للخروج',    'en' => 'Men\'s Outerwear'],
                ['ar' => 'ملابس رجالي للبيت',     'en' => 'Men\'s Home Wear'],
                ['ar' => 'ملابس رجالي داخلية',    'en' => 'Men\'s Underwear'],
                ['ar' => 'بدل رجالي',              'en' => 'Men\'s Suits'],
            ],
            'ملابس أطفال "بنات"' => [
                ['ar' => 'ملابس بنات للخروج',     'en' => 'Girls\' Outerwear'],
                ['ar' => 'ملابس بنات للبيت',      'en' => 'Girls\' Home Wear'],
                ['ar' => 'ملابس بنات داخلية',     'en' => 'Girls\' Underwear'],
                ['ar' => 'ملابس بنات للمدارس',    'en' => 'Girls\' School Uniforms'],
            ],
            'ملابس أطفال "أولاد"' => [
                ['ar' => 'ملابس أولاد للخروج',    'en' => 'Boys\' Outerwear'],
                ['ar' => 'ملابس أولاد للبيت',     'en' => 'Boys\' Home Wear'],
                ['ar' => 'ملابس أولاد داخلية',    'en' => 'Boys\' Underwear'],
                ['ar' => 'ملابس أولاد للمدارس',   'en' => 'Boys\' School Uniforms'],
            ],
            'ملابس رياضية' => [
                ['ar' => 'ملابس نسائية رياضية',   'en' => 'Women\'s Sportswear'],
                ['ar' => 'ملابس رجالي رياضية',    'en' => 'Men\'s Sportswear'],
                ['ar' => 'ملابس بنات رياضية',     'en' => 'Girls\' Sportswear'],
                ['ar' => 'ملابس أولاد رياضية',    'en' => 'Boys\' Sportswear'],
            ],
            'ملابس مهنية' => [
                ['ar' => 'ملابس أطباء وتمريض',    'en' => 'Medical & Nursing Uniforms'],
                ['ar' => 'ملابس محاماه',           'en' => 'Legal Uniforms'],
                ['ar' => 'ملابس طيارين',           'en' => 'Pilot Uniforms'],
                ['ar' => 'ملابس مضيفات',           'en' => 'Flight Attendant Uniforms'],
                ['ar' => 'ملابس مهندسين',          'en' => 'Engineering Uniforms'],
                ['ar' => 'ملابس عمال',             'en' => 'Workwear'],
                ['ar' => 'ملابس حراس أمن',         'en' => 'Security Guard Uniforms'],
                ['ar' => 'ملابس طباخ وحلواني',     'en' => 'Chef & Pastry Cook Uniforms'],
            ],
            'ملابس ومستلزمات المواليد' => [
                ['ar' => 'ملابس مواليد بنات',     'en' => 'Baby Girl Clothes'],
                ['ar' => 'ملابس مواليد أولاد',    'en' => 'Baby Boy Clothes'],
                ['ar' => 'مستلزمات مواليد',        'en' => 'Baby Accessories'],
            ],
            'شنط وأحزمة ومحافظ' => [
                ['ar' => 'شنط نسائية',            'en' => 'Women\'s Bags'],
                ['ar' => 'شنط رجالي',             'en' => 'Men\'s Bags'],
                ['ar' => 'شنط بنات',              'en' => 'Girls\' Bags'],
                ['ar' => 'شنط سفر',               'en' => 'Travel Bags'],
                ['ar' => 'شنط مدارس',             'en' => 'School Bags'],
                ['ar' => 'شنط لاب توب',           'en' => 'Laptop Bags'],
                ['ar' => 'شنط للنادي',            'en' => 'Gym Bags'],
                ['ar' => 'شنط تسوق',              'en' => 'Shopping Bags'],
                ['ar' => 'أحزمة رجالي',           'en' => 'Men\'s Belts'],
                ['ar' => 'أحزمة نسائية',          'en' => 'Women\'s Belts'],
                ['ar' => 'محافظ نقود',            'en' => 'Wallets'],
            ],
            'أحذية جلد' => [
                ['ar' => 'أحذية جلد نسائية',     'en' => 'Women\'s Leather Shoes'],
                ['ar' => 'أحذية جلد رجالي',      'en' => 'Men\'s Leather Shoes'],
                ['ar' => 'أحذية جلد بنات',       'en' => 'Girls\' Leather Shoes'],
                ['ar' => 'أحذية جلد أولاد',      'en' => 'Boys\' Leather Shoes'],
            ],
            'أحذية رياضية' => [
                ['ar' => 'أحذية رياضية نسائية',  'en' => 'Women\'s Sports Shoes'],
                ['ar' => 'أحذية رياضية رجالي',   'en' => 'Men\'s Sports Shoes'],
                ['ar' => 'أحذية رياضية بنات',    'en' => 'Girls\' Sports Shoes'],
                ['ar' => 'أحذية رياضية أولاد',   'en' => 'Boys\' Sports Shoes'],
            ],
            'شباشب وصنادل' => [
                ['ar' => 'شباشب وصنادل نسائية',  'en' => 'Women\'s Slippers & Sandals'],
                ['ar' => 'شباشب وصنادل رجالي',   'en' => 'Men\'s Slippers & Sandals'],
                ['ar' => 'شباشب وصنادل بنات',    'en' => 'Girls\' Slippers & Sandals'],
                ['ar' => 'شباشب وصنادل أولاد',   'en' => 'Boys\' Slippers & Sandals'],
            ],
            'شرابات "جوارب"' => [
                ['ar' => 'شرابات "جوارب" نسائية', 'en' => 'Women\'s Socks'],
                ['ar' => 'شرابات "جوارب" رجالي',  'en' => 'Men\'s Socks'],
                ['ar' => 'شرابات "جوارب" بنات',   'en' => 'Girls\' Socks'],
                ['ar' => 'شرابات "جوارب" أولاد',  'en' => 'Boys\' Socks'],
            ],
            'أدوات ومستلزمات شخصية' => [
                ['ar' => 'إكسسوارات ومستلزمات نسائية', 'en' => 'Women\'s Accessories'],
                ['ar' => 'إكسسوارات ومستلزمات بنات',   'en' => 'Girls\' Accessories'],
                ['ar' => 'أدوات ومستلزمات رجالي',       'en' => 'Men\'s Personal Tools & Accessories'],
                ['ar' => 'أدوات ومستلزمات أولاد',       'en' => 'Boys\' Personal Tools & Accessories'],
            ],
            'أقمشة ملابس' => [
                ['ar' => 'أقمشة ملابس نسائية',   'en' => 'Women\'s Clothing Fabrics'],
                ['ar' => 'أقمشة ملابس رجالي',    'en' => 'Men\'s Clothing Fabrics'],
            ],
            'أقمشة مفروشات وتنجيد' => [
                ['ar' => 'أقمشة مفروشات',         'en' => 'Furniture Fabrics'],
                ['ar' => 'قطن تنجيد',             'en' => 'Upholstery Cotton'],
                ['ar' => 'اسفنج تنجيد',           'en' => 'Upholstery Foam'],
                ['ar' => 'فايبر تنجيد',           'en' => 'Upholstery Fiber'],
                ['ar' => 'مستلزمات تنجيد',        'en' => 'Upholstery Supplies'],
            ],
            'مفروشات ومراتب وستائر' => [
                ['ar' => 'مفروشات سراير',         'en' => 'Bed Linens'],
                ['ar' => 'بطاطين',                'en' => 'Blankets'],
                ['ar' => 'مراتب',                 'en' => 'Mattresses'],
                ['ar' => 'مخدات',                 'en' => 'Pillows'],
                ['ar' => 'ستائر منزلية',          'en' => 'Home Curtains'],
                ['ar' => 'ستائر مكتبية',          'en' => 'Office Curtains'],
                ['ar' => 'مستلزمات ستائر',        'en' => 'Curtain Accessories'],
            ],
            'سجاد وفرش أرضيات' => [
                ['ar' => 'سجاد وموكيت',           'en' => 'Carpets & Rugs'],
                ['ar' => 'دواسات أرضيات',         'en' => 'Floor Mats'],
                ['ar' => 'أرضيات مشمع وجلد',      'en' => 'Vinyl & Leather Flooring'],
                ['ar' => 'أرضيات فوم',            'en' => 'Foam Flooring'],
                ['ar' => 'أرضيات بلاستيك',        'en' => 'Plastic Flooring'],
                ['ar' => 'أرضيات خشب',            'en' => 'Wooden Flooring'],
                ['ar' => 'عوازل أرضيات',          'en' => 'Floor Insulation'],
                ['ar' => 'نجيل صناعي',            'en' => 'Artificial Grass'],
            ],
            'هدايا ومقتنيات متنوعة' => [
                ['ar' => 'نظارت شمسية نسائية',    'en' => 'Women\'s Sunglasses'],
                ['ar' => 'نظارت شمسية رجالي',     'en' => 'Men\'s Sunglasses'],
                ['ar' => 'نظارت شمسية أطفال',     'en' => 'Kids\' Sunglasses'],
                ['ar' => 'نظارات طبية',           'en' => 'Prescription Glasses'],
                ['ar' => 'هدايا ومقتنيات متنوعة', 'en' => 'Gifts & Collectibles'],
                ['ar' => 'شنط وأكياس هدايا',      'en' => 'Gift Bags & Wrapping'],
                ['ar' => 'كؤوس',                  'en' => 'Trophies & Cups'],
                ['ar' => 'دروع ونياشين',          'en' => 'Shields & Medals'],
                ['ar' => 'ميداليات',              'en' => 'Medallions'],
                ['ar' => 'مجسمات',                'en' => 'Figurines & Models'],
                ['ar' => 'هدايا تذكارية',         'en' => 'Souvenirs'],
                ['ar' => 'خردوات وأدوات متنوعة',  'en' => 'Miscellaneous Tools & Gadgets'],
                ['ar' => 'مستلزمات دعاية',        'en' => 'Promotional Supplies'],
                ['ar' => 'زينة للمناسبات',        'en' => 'Event Decorations'],
            ],
            'منتجات عطور وعناية بالجسم' => [
                ['ar' => 'عطور نسائية',           'en' => 'Women\'s Perfumes'],
                ['ar' => 'عطور رجالي',            'en' => 'Men\'s Perfumes'],
                ['ar' => 'منتجات جمال المرأة',    'en' => 'Women\'s Beauty Products'],
                ['ar' => 'منتجات العناية بالجسم', 'en' => 'Body Care Products'],
            ],
            'منتجات نظافة وعناية بالمنزل' => [
                ['ar' => 'منتجات النظافة',         'en' => 'Cleaning Products'],
                ['ar' => 'منتجات العناية بالمنزل', 'en' => 'Home Care Products'],
            ],
            'أثاث وأدوات منزلية وديكورات' => [
                ['ar' => 'أثاث غرف النوم',                  'en' => 'Bedroom Furniture'],
                ['ar' => 'أثاث السفرة',                     'en' => 'Dining Room Furniture'],
                ['ar' => 'أثاث الصالون',                    'en' => 'Living Room Furniture'],
                ['ar' => 'أثاث الأنتريه',                   'en' => 'Entrance Hall Furniture'],
                ['ar' => 'أثاث الركنة',                     'en' => 'Corner Sofas'],
                ['ar' => 'مطابخ',                            'en' => 'Kitchen Furniture'],
                ['ar' => 'أثاث متنوع للمنزل',               'en' => 'Miscellaneous Home Furniture'],
                ['ar' => 'أثاث حدائق',                      'en' => 'Garden Furniture'],
                ['ar' => 'أبواب',                            'en' => 'Doors'],
                ['ar' => 'شبابيك',                           'en' => 'Windows'],
                ['ar' => 'أرفف',                             'en' => 'Shelves'],
                ['ar' => 'مستلزمات موبيليات وأبواب وشبابيك', 'en' => 'Furniture, Door & Window Accessories'],
                ['ar' => 'مستلزمات ديكورات',                'en' => 'Decoration Supplies'],
                ['ar' => 'تابلوهات ومرايا',                 'en' => 'Paintings & Mirrors'],
                ['ar' => 'مستلزمات متنوعة للمنزل',          'en' => 'Miscellaneous Home Supplies'],
            ],
            'أجهزة ومستلزمات المطبخ' => [
                ['ar' => 'أجهزة تحضير طعام',       'en' => 'Food Preparation Appliances'],
                ['ar' => 'مستلزمات تحضير طعام',    'en' => 'Food Preparation Supplies'],
                ['ar' => 'أدوات ومستلزمات السفرة', 'en' => 'Dining Tools & Supplies'],
                ['ar' => 'أدوات وسلال تخزين',      'en' => 'Storage Tools & Baskets'],
            ],
            'أجهزة المنزلية' => [
                ['ar' => 'ثلاجات',              'en' => 'Refrigerators'],
                ['ar' => 'ديب فريزر',           'en' => 'Deep Freezers'],
                ['ar' => 'غسالات',              'en' => 'Washing Machines'],
                ['ar' => 'بوتاجازات',           'en' => 'Gas Stoves'],
                ['ar' => 'أفران',               'en' => 'Ovens'],
                ['ar' => 'ميكروويف',            'en' => 'Microwave Ovens'],
                ['ar' => 'مكانس كهربائية',      'en' => 'Vacuum Cleaners'],
                ['ar' => 'أجهزة تكييف',         'en' => 'Air Conditioners'],
                ['ar' => 'مراوح وشفاطات',       'en' => 'Fans & Exhaust Hoods'],
                ['ar' => 'مكواة ملابس',         'en' => 'Clothes Irons'],
                ['ar' => 'سخان غاز',            'en' => 'Gas Water Heaters'],
                ['ar' => 'سخان كهربائي',        'en' => 'Electric Water Heaters'],
                ['ar' => 'دفاية كهربائية',      'en' => 'Electric Heaters'],
                ['ar' => 'مصائد حشرات',         'en' => 'Insect Traps'],
            ],
            'شاشات وأجهزة إستقبال وعرض' => [
                ['ar' => 'شاشات تليفزيون',                   'en' => 'Television Screens'],
                ['ar' => 'أجهزة ومستلزمات إستقبال مرئي',    'en' => 'Visual Reception Devices & Accessories'],
                ['ar' => 'أجهزة ومستلزمات عرض مرئي',        'en' => 'Visual Display Devices & Accessories'],
            ],
            'موبايلات وأجهزة ذكية ومستلزماتها' => [
                ['ar' => 'موبايلات',                          'en' => 'Mobile Phones'],
                ['ar' => 'أجهزة لوحية ذكية',                 'en' => 'Tablets & Smart Devices'],
                ['ar' => 'مستلزمات موبايلات وأجهزة ذكية',   'en' => 'Mobile & Smart Device Accessories'],
            ],
            'أجهزة ومستلزمات الكمبيوتر' => [
                ['ar' => 'لاب توب',                     'en' => 'Laptops'],
                ['ar' => 'كمبيوتر',                     'en' => 'Desktop Computers'],
                ['ar' => 'شاشات كمبيوتر',               'en' => 'Computer Monitors'],
                ['ar' => 'طاولات كمبيوتر',              'en' => 'Computer Desks'],
                ['ar' => 'مستلزمات كمبيوتر متنوعة',     'en' => 'Miscellaneous Computer Accessories'],
            ],
            'ماكينات تصوير وطباعة واسكانر' => [
                ['ar' => 'طابعات مستندات واسكانر',             'en' => 'Document Printers & Scanners'],
                ['ar' => 'ماكينات تصوير مستندات',             'en' => 'Document Copying Machines'],
                ['ar' => 'ماكينات طباعة خرائط',               'en' => 'Map Printing Machines'],
                ['ar' => 'ماكينات طباعة تاريخ',               'en' => 'Date Printing Machines'],
                ['ar' => 'ماكينات طباعة بار كود',             'en' => 'Barcode Printing Machines'],
                ['ar' => 'ماكينات طباعة منتجات وأسطح',        'en' => 'Product & Surface Printing Machines'],
                ['ar' => 'مستلزمات ماكينات طباعة وتصوير',     'en' => 'Printing & Copying Machine Supplies'],
                ['ar' => 'أحبار طابعات',                       'en' => 'Printer Inks & Toners'],
                ['ar' => 'ماكينات حفر ليزر ومستلزماتها',      'en' => 'Laser Engraving Machines & Accessories'],
            ],
            'كاميرات ومستلزمات تصوير' => [
                ['ar' => 'كاميرات تصوير',          'en' => 'Cameras'],
                ['ar' => 'مستلزمات تصوير',         'en' => 'Photography Accessories'],
                ['ar' => 'مستلزمات إستوديوهات',   'en' => 'Studio Supplies'],
            ],
            'أجهزة ومستلزمات صوتيات' => [
                ['ar' => 'ميكروفونات',                  'en' => 'Microphones'],
                ['ar' => 'مكبرات صوت',                  'en' => 'Speakers'],
                ['ar' => 'سماعات رأس',                  'en' => 'Headphones'],
                ['ar' => 'أجهزة ومستلزمات صوتيات',     'en' => 'Audio Devices & Accessories'],
            ],
            'ساعات' => [
                ['ar' => 'ساعات نسائية',           'en' => 'Women\'s Watches'],
                ['ar' => 'ساعات رجالي',            'en' => 'Men\'s Watches'],
                ['ar' => 'ساعات أولاد وبنات',      'en' => 'Kids\' Watches'],
                ['ar' => 'ساعات حائط',             'en' => 'Wall Clocks'],
                ['ar' => 'ساعات مكتب',             'en' => 'Desk Clocks'],
                ['ar' => 'ساعات مواقيت الصلاة',    'en' => 'Prayer Time Clocks'],
                ['ar' => 'مستلزمات ساعات',         'en' => 'Watch Accessories'],
            ],
            'أنظمة أمن وتتبع ومراقبة وسلامة' => [
                ['ar' => 'أنظمة ومستلزمات كاميرات مراقبة', 'en' => 'Surveillance Camera Systems & Accessories'],
                ['ar' => 'أنظمة ومستلزمات إنذار سرقة',    'en' => 'Theft Alarm Systems & Accessories'],
                ['ar' => 'أنظمة ومستلزمات إنذار حريق',    'en' => 'Fire Alarm Systems & Accessories'],
                ['ar' => 'أنظمة ومستلزمات تتبع GPS',      'en' => 'GPS Tracking Systems & Accessories'],
                ['ar' => 'أنظمة ومستلزمات أمنية',          'en' => 'General Security Systems & Accessories'],
            ],
            'إلكترونيات متنوعة' => [
                ['ar' => 'أجهزة إلكترونية متنوعة',    'en' => 'Miscellaneous Electronic Devices'],
                ['ar' => 'مستلزمات إلكترونية متنوعة', 'en' => 'Miscellaneous Electronic Accessories'],
            ],
            'مستلزمات مكتبية وتعليمية' => [
                ['ar' => 'أجهزة مكتبية',          'en' => 'Office Devices'],
                ['ar' => 'مستلزمات مكتبية',       'en' => 'Office Supplies'],
                ['ar' => 'مستلزمات مدرسية',       'en' => 'School Supplies'],
                ['ar' => 'مستلزمات تعليمية',      'en' => 'Educational Supplies'],
                ['ar' => 'مستلزمات فنية',         'en' => 'Art Supplies'],
                ['ar' => 'أشغال يدوية وفنية',     'en' => 'Handicrafts & Art Projects'],
                ['ar' => 'آلات حاسبة',            'en' => 'Calculators'],
                ['ar' => 'أجهزة علمية',           'en' => 'Scientific Devices'],
                ['ar' => 'برمجيات',               'en' => 'Software'],
                ['ar' => 'ألعاب إلكترونية',       'en' => 'Electronic Games'],
                ['ar' => 'ألعاب أطفال',           'en' => 'Children\'s Toys'],
            ],
            'كتب وقصص ومطبوعات' => [
                ['ar' => 'مصاحف وكتب إسلامية',   'en' => 'Qurans & Islamic Books'],
                ['ar' => 'كتب مدرسية',            'en' => 'Schoolbooks'],
                ['ar' => 'كتب تعليمية أخرى',      'en' => 'Other Educational Books'],
                ['ar' => 'كتب وقصص عربية',        'en' => 'Arabic Books & Stories'],
                ['ar' => 'كتب وقصص أجنبية',       'en' => 'Foreign Books & Stories'],
                ['ar' => 'مطبوعات متنوعة',        'en' => 'Miscellaneous Publications'],
            ],
            'منتجات للصحة والطاقة والرجيم' => [],
            'أجهزة ومستلزمات طبية' => [
                ['ar' => 'أجهزة ومعدات طبية',               'en' => 'Medical Devices & Equipment'],
                ['ar' => 'قطع غيار أجهزة ومعدات طبية',     'en' => 'Medical Device Spare Parts'],
                ['ar' => 'أدوات ومستلزمات طبية',            'en' => 'Medical Tools & Supplies'],
                ['ar' => 'منتجات رعاية طبية',               'en' => 'Medical Care Products'],
            ],
            'أجهزة ومستلزمات رياضة ولياقة وترفيه' => [
                ['ar' => 'أجهزة رياضة ولياقة بدنية',       'en' => 'Sports & Fitness Devices'],
                ['ar' => 'مستلزمات رياضة ولياقة بدنية',    'en' => 'Sports & Fitness Supplies'],
                ['ar' => 'مستلزمات سباحة وغوص',            'en' => 'Swimming & Diving Supplies'],
                ['ar' => 'مستلزمات صيد سمك',               'en' => 'Fishing Supplies'],
                ['ar' => 'مستلزمات صيد بري',               'en' => 'Hunting Supplies'],
                ['ar' => 'مستلزمات رحلات وتخييم',          'en' => 'Travel & Camping Supplies'],
            ],
            'مستلزمات نجارة وسباكة ودهان' => [
                ['ar' => 'مستلزمات نجارة',        'en' => 'Carpentry Supplies'],
                ['ar' => 'مستلزمات سباكة',        'en' => 'Plumbing Supplies'],
                ['ar' => 'فلاتر مياه',            'en' => 'Water Filters'],
                ['ar' => 'مستلزمات دهان',         'en' => 'Painting Supplies'],
                ['ar' => 'عدد وأدوات حرفية',      'en' => 'Hand Tools & Craft Tools'],
            ],
            'أطقم حمامات وسيراميك ورخام' => [
                ['ar' => 'أطقم حمامات',           'en' => 'Bathroom Sets'],
                ['ar' => 'سيراميك',               'en' => 'Ceramics'],
                ['ar' => 'رخام',                  'en' => 'Marble'],
            ],
            'أنظمة ومستلزمات كهرباء وإنارة' => [
                ['ar' => 'نجف ولمبات وأنظمة إنارة',         'en' => 'Chandeliers, Bulbs & Lighting Systems'],
                ['ar' => 'مستلزمات توصيلات كهربائية',       'en' => 'Electrical Wiring Supplies'],
                ['ar' => 'أنظمة اطاقة شمسية',              'en' => 'Solar Energy Systems'],
                ['ar' => 'مولدات كهرباء',                   'en' => 'Electric Generators'],
                ['ar' => 'محولات كهرباء',                   'en' => 'Electrical Transformers'],
                ['ar' => 'أجهزة شحن بطاريات',              'en' => 'Battery Chargers'],
                ['ar' => 'بطاريات قابلة للشحن',            'en' => 'Rechargeable Batteries'],
                ['ar' => 'بطاريات أخرى',                   'en' => 'Other Batteries'],
            ],
            'سيارات كهربائية وجولف وبيتش وأطفال' => [
                ['ar' => 'سيارات كهربائية ومستلزماتها',    'en' => 'Electric Cars & Accessories'],
                ['ar' => 'سيارات جولف ومستلزماتها',        'en' => 'Golf Cars & Accessories'],
                ['ar' => 'بيتش باجي ومستلزماتها',          'en' => 'Beach Buggies & Accessories'],
                ['ar' => 'سيارات اطفال ومستلزماتها',       'en' => 'Kids\' Cars & Accessories'],
            ],
            'تكاتك وموتوسيكلات ودراجات واسكوترات' => [
                ['ar' => 'تكاتك ومستلزماتها',         'en' => 'Tuk-tuks & Accessories'],
                ['ar' => 'تروسيكلات ومستلزماتها',     'en' => 'Tricycles & Accessories'],
                ['ar' => 'موتوسيكلات ومستلزماتها',    'en' => 'Motorcycles & Accessories'],
                ['ar' => 'فسب ومستلزماتها',           'en' => 'Vespas & Accessories'],
                ['ar' => 'اسكوترات ومستلزماتها',      'en' => 'Scooters & Accessories'],
                ['ar' => 'دراجات ومستلزماتها',        'en' => 'Bicycles & Accessories'],
            ],
            'مستلزمات وكماليات السيارات' => [
                ['ar' => 'منتجات عناية بالسيارات',    'en' => 'Car Care Products'],
                ['ar' => 'كماليات وزينة السيارات',    'en' => 'Car Accessories & Styling'],
                ['ar' => 'شاشات سيارات',              'en' => 'Car Screens'],
                ['ar' => 'جنوط سيارات',               'en' => 'Car Rims'],
                ['ar' => 'كاوتش سيارات',              'en' => 'Car Tires'],
                ['ar' => 'بطاريات سيارات',            'en' => 'Car Batteries'],
                ['ar' => 'كوريك سيارات',              'en' => 'Car Jacks'],
                ['ar' => 'أغطية سيارات',              'en' => 'Car Covers'],
                ['ar' => 'طفايات حريق للسيارات',      'en' => 'Car Fire Extinguishers'],
            ],
            'أثاث شركات ومكاتب' => [
                ['ar' => 'مكاتب مديرين وموظفين وطلاب',    'en' => 'Manager, Employee & Student Desks'],
                ['ar' => 'مكاتب إستقبال',                 'en' => 'Reception Desks'],
                ['ar' => 'كراسي مكاتب وكراسي إنتظار',    'en' => 'Office Chairs & Waiting Chairs'],
                ['ar' => 'طاولات إجتماعات',               'en' => 'Meeting Tables'],
                ['ar' => 'بارتيشن مكاتب',                 'en' => 'Office Partitions'],
                ['ar' => 'وحدات دواليب وأدراج مكتبية',   'en' => 'Office Cabinets & Drawers'],
                ['ar' => 'مستلزمات وإكسسوارات مكاتب',    'en' => 'Office Supplies & Accessories'],
                ['ar' => 'ماكينات عد نقود',               'en' => 'Money Counting Machines'],
                ['ar' => 'خزائن نقود',                    'en' => 'Cash Safes'],
                ['ar' => 'أثاث فنادق',                    'en' => 'Hotel Furniture'],
                ['ar' => 'أثاث مطاعم',                    'en' => 'Restaurant Furniture'],
                ['ar' => 'أثاث مستشفيات',                 'en' => 'Hospital Furniture'],
            ],
            'تجهيزات محلات ومعارض ومخازن' => [
                ['ar' => 'أرفف عرض وتخزين',               'en' => 'Display & Storage Shelves'],
                ['ar' => 'مستلزمات عرض وتخزين',           'en' => 'Display & Storage Supplies'],
                ['ar' => 'ثلاجات عرض وتخزين',             'en' => 'Display & Storage Refrigerators'],
                ['ar' => 'أبواب محلات',                   'en' => 'Shop Doors'],
                ['ar' => 'مستلزمات أبواب محلات',          'en' => 'Shop Door Accessories'],
                ['ar' => 'ماكينات تسعير',                 'en' => 'Pricing Machines'],
                ['ar' => 'مكاتب كاشير',                   'en' => 'Cashier Desks'],
                ['ar' => 'أجهزة كاشير وملحقاتها',         'en' => 'POS Devices & Accessories'],
                ['ar' => 'برامج كاشير ومخزون ومبيعات',    'en' => 'POS, Inventory & Sales Software'],
                ['ar' => 'عربات وسلال تسوق',              'en' => 'Shopping Carts & Baskets'],
                ['ar' => 'معدات رفع بضائع',               'en' => 'Goods Lifting Equipment'],
                ['ar' => 'معدات وأدوات ربط وتغليف',       'en' => 'Binding & Packaging Tools'],
                ['ar' => 'تجهيزات كافيهات',               'en' => 'Café Equipment'],
                ['ar' => 'تجهيزات كوافير وحلاقين',        'en' => 'Salon & Barbershop Equipment'],
            ],
            'ماكينات وأجهزة ومعدات' => [
                ['ar' => 'ماكينات وأجهزة ومعدات صناعية',   'en' => 'Industrial Machines & Equipment'],
                ['ar' => 'ماكينات وأجهزة ومعدات تجارية',   'en' => 'Commercial Machines & Equipment'],
                ['ar' => 'ماكينات وأجهزة ومعدات زراعية',   'en' => 'Agricultural Machines & Equipment'],
                ['ar' => 'ماكينات وأجهزة مكتبية',          'en' => 'Office Machines & Devices'],
                ['ar' => 'أجهزة ومعدات مطاعم ومطابخ',     'en' => 'Restaurant & Kitchen Equipment'],
                ['ar' => 'أجهزة ومعدات حلواني ومخابز',    'en' => 'Pastry & Bakery Equipment'],
                ['ar' => 'مغاسل ومصابغ ملابس',             'en' => 'Laundry & Dry-Cleaning Equipment'],
                ['ar' => 'مغاسل سيارات',                   'en' => 'Car Wash Equipment'],
                ['ar' => 'أجهزة ومعدات مطابع',             'en' => 'Printing Press Equipment'],
                ['ar' => 'أجهزة ومعدات ورش',               'en' => 'Workshop Equipment'],
                ['ar' => 'أجهزة ومعدات معامل',             'en' => 'Laboratory Equipment'],
                ['ar' => 'ماكينات ومعدات حفر وبناء وطرق',  'en' => 'Excavation, Construction & Road Equipment'],
            ],
            'قطع غيار' => [
                ['ar' => 'قطع غيار سيارات',               'en' => 'Car Spare Parts'],
                ['ar' => 'قطع غيار أجهزة منزلية',         'en' => 'Home Appliance Spare Parts'],
                ['ar' => 'قطع غيار أجهزة مكتبية',         'en' => 'Office Device Spare Parts'],
                ['ar' => 'قطع غيار معدات صناعية',         'en' => 'Industrial Equipment Spare Parts'],
                ['ar' => 'قطع غيار معدات تجارية',         'en' => 'Commercial Equipment Spare Parts'],
                ['ar' => 'قطع غيار معدات زراعية',         'en' => 'Agricultural Equipment Spare Parts'],
                ['ar' => 'قطع غيار معدات حفر وبناء وطرق', 'en' => 'Excavation & Construction Equipment Spare Parts'],
            ],
            'ماكينات ومستلزمات الملابس' => [
                ['ar' => 'ماكينات قص قماش',                     'en' => 'Fabric Cutting Machines'],
                ['ar' => 'ماكينات خياطة صناعية',                'en' => 'Industrial Sewing Machines'],
                ['ar' => 'ماكينات خياطة منزلية',                'en' => 'Home Sewing Machines'],
                ['ar' => 'ماكينات تريكو',                       'en' => 'Knitting Machines'],
                ['ar' => 'ماكينات تطريز',                       'en' => 'Embroidery Machines'],
                ['ar' => 'مستلزمات خياطة وتطريز وتريكو',       'en' => 'Sewing, Embroidery & Knitting Supplies'],
                ['ar' => 'قطع غيار خياطة وتطريز وتريكو',       'en' => 'Sewing, Embroidery & Knitting Spare Parts'],
            ],
            'أعلاف وأطعمة حيوانات وطيور وأسماك' => [
                ['ar' => 'أعلاف مواشي ودواجن وأسماك',      'en' => 'Livestock, Poultry & Fish Feed'],
                ['ar' => 'أطعمة حيوانات وطيور أليفة',      'en' => 'Pet Food'],
                ['ar' => 'أطعمة أسماك زينة',               'en' => 'Ornamental Fish Food'],
                ['ar' => 'مستلزمات مواشي ودواجن وأسماك',   'en' => 'Livestock, Poultry & Fish Supplies'],
                ['ar' => 'مستلزمات حيوانات وطيور أليفة',   'en' => 'Pet Supplies'],
                ['ar' => 'مستلزمات أسماك زينة',            'en' => 'Ornamental Fish Supplies'],
            ],
            'أسمدة ومواد وأدوات زراعية' => [
                ['ar' => 'أسمدة ومخصبات',                    'en' => 'Fertilizers & Plant Nutrients'],
                ['ar' => 'بذور وتقاوي',                      'en' => 'Seeds & Seedlings'],
                ['ar' => 'مبيدات زراعية',                    'en' => 'Pesticides'],
                ['ar' => 'تربة زراعية ومحسنات',             'en' => 'Agricultural Soil & Amendments'],
                ['ar' => 'مستلزمات زراعة ومشاتل وحدائق',   'en' => 'Farming, Nursery & Garden Supplies'],
            ],
            'سوبر ماركت لولو' => [
                ['ar' => 'منتجات لحوم',                        'en' => 'Meat Products'],
                ['ar' => 'منتجات دواجن',                       'en' => 'Poultry Products'],
                ['ar' => 'فواكه وخضروات طازجة',               'en' => 'Fresh Fruits & Vegetables'],
                ['ar' => 'فواكه وخضروات مجمدة',               'en' => 'Frozen Fruits & Vegetables'],
                ['ar' => 'أجبان ومنتجات ألبان',               'en' => 'Cheese & Dairy Products'],
                ['ar' => 'بقوليات',                            'en' => 'Legumes & Pulses'],
                ['ar' => 'معلبات وأغذية مغلفة',               'en' => 'Canned & Packaged Foods'],
                ['ar' => 'شوكولاتة وبسكويت وسكاكر',           'en' => 'Chocolate, Biscuits & Candy'],
                ['ar' => 'عصائر ومشروبات وأيس كريم',          'en' => 'Juices, Beverages & Ice Cream'],
                ['ar' => 'عطارة',                              'en' => 'Spices & Herbs'],
                ['ar' => 'تمور ومكسرات وتسالي',               'en' => 'Dates, Nuts & Snacks'],
                ['ar' => 'حلويات ومخبوزات',                   'en' => 'Sweets & Baked Goods'],
                ['ar' => 'خامات الحلويات والمخبوزات',         'en' => 'Pastry & Baking Ingredients'],
            ],
        ];

        foreach ($data as $mainCategoryAr => $subCategories) {
            $mainCategoryId = $mainCategoryIds[$mainCategoryAr] ?? null;

            if (!$mainCategoryId) {
                continue;
            }

            foreach ($subCategories as $sub) {
                $slug = Str::slug($sub['en']);

                $categoryId = DB::table('categories')->insertGetId([
                    'name'             => $sub['en'],
                    'slug'             => $slug,
                    'image'            => null,
                    'main_category_id' => $mainCategoryId,
                    'is_active'        => true,
                    'type'             => 'piece',
                    'created_at'       => now(),
                    'updated_at'       => now(),
                ]);

                DB::table('category_translations')->insert([
                    [
                        'category_id' => $categoryId,
                        'locale'      => 'ar',
                        'name'        => $sub['ar'],
                        'slug'        => $slug . '-ar',
                        'created_at'  => now(),
                        'updated_at'  => now(),
                    ],
                    [
                        'category_id' => $categoryId,
                        'locale'      => 'en',
                        'name'        => $sub['en'],
                        'slug'        => $slug,
                        'created_at'  => now(),
                        'updated_at'  => now(),
                    ],
                ]);
            }
        }
    }
}
